project:
  type: book
  output-dir: docs

lang: de

book:
  title: "Einführung in R"
  subtitle: "Lehrstuhl für VWL, insb. Wirtschaftspolitik, Fernuniversität in Hagen"
  chapters:
    - index.qmd
    
    - part: "Grundlagen"
      chapters:
        - erste_schritte.qmd
        - best_practices.qmd

  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme: 
      - cosmo
      - style.scss
    code-link: true
    author-meta: "Andreas Fischeneder"
    callout-appearance: simple

execute:
  freeze: auto
  warning: false
  message: false